version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: orders
        identifier: orders_us
      - name: deliveries
      - name: customers
        description: Customer data from our ecommerce application
        columns:
          - name: id
            description: '{{ doc("customer_id") }}'
     
  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses