version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: deliveries
      - name: customers
        description: Customer data from our ecommerce application
        columns:
          - name: id
            description: '{{ doc("customer_id") }}'